### ISSUE TITLE
Custom PPA should be removed

### ISSUE THREAD

**Issue by ChrisMacNaughton** [canonical/ceph-containers#6]
After the linked bugs [1][2] are resolved, the PPA used in the CI should be removed.

1: https://bugs.launchpad.net/ubuntu/+source/ceph/+bug/2003704
2: https://bugs.launchpad.net/ubuntu/+source/ceph/+bug/2003530

**Comment by UtkarshBhatthere** [comment]
Although this was created earlier, but is a valid issue today as well due to the ceph-fs-mirror binary's absence in ubuntu packages. See [this](https://code.launchpad.net/~peter-sabaini/ubuntu/+source/ceph/+git/ceph/+merge/436234)

**Comment by UtkarshBhatthere** [comment]
Marking this issue closed. :D
